# Derived from external-provisioner-config.yaml, modified and maintained manually.

presubmits:
  kubernetes-csi/external-provisioner:
  - name: pull-kubernetes-csi-external-provisioner-distributed-on-kubernetes-1-21
    always_run: true
    optional: false
    decorate: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      testgrid-dashboards: sig-storage-csi-external-provisioner
      testgrid-tab-name: distributed-on-kubernetes-master
      description: Kubernetes-CSI pull job in repo external-provisioner for distributed provisioning, with CSIStorageCapacity
    spec:
      containers:
      # We need this image because it has Docker in Docker and go.
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210512-b8d1b30-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        env:
        - name: CSI_PROW_KUBERNETES_VERSION
          value: "1.21.0"
        - name: CSI_PROW_USE_BAZEL
          value: "true"
        - name: CSI_PROW_DRIVER_VERSION
          value: "v1.7.2"
        - name: CSI_SNAPSHOTTER_VERSION
          value: "v4.0.0"
        - name: CSI_PROW_TESTS
          value: "sanity serial parallel serial-alpha parallel-alpha"
        - name: CSI_PROW_SANITY_POD
          value: csi-hostpath-socat-0
        - name: CSI_PROW_SANITY_CONTAINER
          value: socat
        - name: CSI_PROW_DEPLOYMENT
          value: "kubernetes-distributed"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
